// src/lib/permissionLabels.ts
export const resourceLabels: Record<string, string> = {
    member:            "Team Members",
    invitation:        "Invitations",
    platformKey:       "Platform API Keys",
    customer:          "Customers",
    ticket:            "Support Tickets",
    order:             "Orders",
    orderChat:         "Order Chat",
    reviews:            "View reviews",
    product:           "Products",
    productCategories: "Product Categories",
    productAttributes: "Product Attributes",
    warehouses:        "Warehouses",
    tierPricing:       "Tier Pricing",
    stockManagement:   "Stock Management",
    coupon:            "Coupons",
    announcements:     "Announcements",
    affiliates:        "Affiliates",
    revenue:           "Revenue Reports",
    categoriesReport:  "Category Reports",
    couponsReport:     "Coupon Reports",
    productsReport:    "Product Reports",
    sections:          "Sections",
    payment:           "Payment Methods",
    shipping:          "Shipping Methods",
    shippingMethods:   "Shipping Companies",
    notifications:     "Notification Templates",
  };
  
  export const actionLabels: Record<string, string> = {
    view:            "View",
    create:          "Create",
    update:          "Update",
    delete:          "Delete",
    update_role:     "Change Role",
    cancel:          "Cancel Invitation",
    export:          "Export",
    sharing:         "Manage Sharing",
    synchronize:     "Sync",
    update_status:   "Update Status",
    view_pricing:    "View Pricing",
    update_tracking: "Update Tracking",
    points:          "Adjust Points",
    settings:        "Settings",
    products:        "Manage Products",
    logs:            "View Logs",
  };
  